services:
    leezy.pheanstalk.proxy.default:
        class: Leezy\PheanstalkBundle\Proxy\PheanstalkProxy
        public: false
        calls:
            - [setDispatcher, ['@?event_dispatcher']]
            
